name: Perovskite_ML_Environment
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - appdirs=1.4.4=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bottleneck=1.3.5=py310ha9d4c09_0
  - brotlipy=0.7.0=py310h7f8727e_1002
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.5.7=hbcca054_0
  - certifi=2023.5.7=pyhd8ed1ab_0
  - cffi=1.15.1=py310h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=39.0.1=py310h9ce1e76_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - jinja2=3.1.2=py310h06a4308_0
  - joblib=1.1.1=py310h06a4308_0
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.6.1.9=0
  - libcurand=10.3.2.106=0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.17=h5eee18b_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libnpp=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.0=h6a678d5_2
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py310h7f8727e_0
  - mkl=2023.1.0=h6d00ec8_46342
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.6=py310h1128e8f_1
  - mkl_random=1.2.2=py310h1128e8f_1
  - mscorefonts=0.0.1=3
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - numexpr=2.8.4=py310h85018f9_1
  - numpy=1.24.3=py310h5f9d8c6_1
  - numpy-base=1.24.3=py310hb5e798b_1
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1t=h7f8727e_0
  - packaging=23.0=py310h06a4308_0
  - pandas=1.5.3=py310h1128e8f_0
  - pillow=9.4.0=py310h6a678d5_0
  - pip=23.0.1=py310h06a4308_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - psutil=5.9.0=py310h5eee18b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyg=2.3.0=py310_torch_1.13.0_cu117
  - pyopenssl=23.0.0=py310h06a4308_0
  - pyparsing=3.0.9=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.11=h7a1cb2a_2
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytorch=1.13.1=py3.10_cuda11.7_cudnn8.5.0_0
  - pytorch-cluster=1.6.1=py310_torch_1.13.0_cu117
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - pytorch-scatter=2.1.1=py310_torch_1.13.0_cu117
  - pytorch-sparse=0.6.17=py310_torch_1.13.0_cu117
  - pytz=2022.7=py310h06a4308_0
  - readline=8.2=h5eee18b_0
  - requests=2.29.0=py310h06a4308_0
  - scikit-learn=1.2.2=py310h6a678d5_0
  - scipy=1.10.1=py310h5f9d8c6_1
  - setuptools=66.0.0=py310h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.13.1=py310_cu117
  - torchvision=0.14.1=py310_cu117
  - tqdm=4.65.0=py310h2f386ee_0
  - typing_extensions=4.5.0=py310h06a4308_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.15=py310h06a4308_0
  - wheel=0.38.4=py310h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
    - ase==3.22.1
    - asttokens==2.2.1
    - backcall==0.2.0
    - backoff==1.11.1
    - beautifulsoup4==4.12.2
    - click==8.1.3
    - comm==0.1.3
    - contourpy==1.0.7
    - cycler==0.11.0
    - debugpy==1.6.7
    - decorator==5.1.1
    - e3fp==1.2.5
    - e3nn==0.5.1
    - emmet-core==0.55.2
    - executing==1.2.0
    - filelock==3.12.0
    - fonttools==4.39.4
    - future==0.18.3
    - gdown==4.7.1
    - gitdb==4.0.10
    - gitpython==3.1.31
    - ipykernel==6.23.1
    - ipython==8.13.2
    - jedi==0.18.2
    - jupyter-client==8.2.0
    - jupyter-core==5.3.0
    - kiwisolver==1.4.4
    - latexcodec==2.0.1
    - matplotlib==3.7.1
    - matplotlib-inline==0.1.6
    - mmh3==4.0.0
    - monty==2023.5.8
    - mp-api==0.33.3
    - mpmath==1.3.0
    - msgpack==1.0.5
    - nest-asyncio==1.5.6
    - networkx==3.1
    - opt-einsum==3.3.0
    - opt-einsum-fx==0.1.4
    - palettable==3.3.3
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - platformdirs==3.5.1
    - plotly==5.14.1
    - prompt-toolkit==3.0.38
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pybtex==0.24.0
    - pydantic==1.10.7
    - pygments==2.15.1
    - pymatgen==2023.5.10
    - pypng==0.20220715.0
    - pyyaml==5.4.1
    - pyzmq==25.0.2
    - rdkit==2023.3.1
    - ruamel-yaml==0.17.26
    - ruamel-yaml-clib==0.2.7
    - sdaxen-python-utilities==0.1.5
    - sigopt==8.8.0
    - smart-open==6.3.0
    - smmap==5.0.0
    - soupsieve==2.4.1
    - spglib==2.0.2
    - stack-data==0.6.2
    - sympy==1.12
    - tabulate==0.9.0
    - tenacity==8.2.2
    - tornado==6.3.2
    - traitlets==5.9.0
    - uncertainties==3.1.7
    - wcwidth==0.2.6
prefix: /home/jypeng/miniconda3/envs/Perovskite_ML_Environment
